version: 0.2

phases:
  install:
    commands:
        - yum update -y
        - yum install httpd -y
        - yum install -y php
        - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
        - php composer-setup.php ;
        - php -r "unlink('composer-setup.php');";
        - mv composer.phar /usr/local/bin/composer       
  build:
   commands:
     - echo Build started on `date`
     - echo Installing composer deps
     - cd /var/www/html
     - composer install --no-progress --no-suggest
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - index.php
    - appspec.yml
    - scripts/install_dependencies.sh
    - scripts/composer_install.sh
    - scripts/start_server.sh
    - scripts/stop_server.sh
