version: 0.2
phases:
 install:
   commands:
     - echo 1
 build:
   commands:
     - echo Build started on `date`
     - echo Installing composer dep
 post_build:
   commands:
     - echo Build completed on `date`
artifacts:
  files:
    - index.php
    - appspec.yml
    - scripts/install_dependencies.sh
    - scripts/composer_install.sh
    - scripts/start_server.sh
    - scripts/stop_server.sh