version: 0.2

phases:
  install:
    commands:
        - echo ok
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Python code...
      - python test_app.py
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - index.php
    - appspec.yml
    - scripts/install_dependencies.sh
    - scripts/composer_install.sh
    - scripts/start_server.sh
    - scripts/stop_server.sh
