version: 0.2
run-as:ec2-user
phases:
  install:
    commands:
        - echo Install dependency  
  build:
   commands:
     - cd scripts
     - ./scripts/install_dependencies.sh
     - ./scripts/composer_install.sh
     - ./scripts/start_server.sh
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - index.php
    - appspec.yml
    - scripts/install_dependencies.sh
    - scripts/composer_install.sh
    - scripts/start_server.sh
    - scripts/stop_server.sh
