version: 0.2

phases:
  install:
    commands:
        - pip install --trusted-host files.pythonhosted.org --trusted-host pypi.org --trusted-host pypi.python.org pip setuptools
        - pip install --upgrade requests
        - pip install --upgrade pyopenssl ndg-httpsclient pyasn1
        - pip install --upgrade flask
        - pip install --upgrade flask
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Python code...
      - python test_app.py
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - web.py
    - appspec.yml
    - templates/layout.html
    - templates/test.html
    - scripts/mkdir.sh
    - scripts/start_flask.sh
    - scripts/stop_flask1.sh
    - scripts/stop_flask.py
